version: '3'

services:
  animal-service:
    image: animal-service:0.0.1-SNAPSHOT
    build:
      context: ./animal-service
      dockerfile: dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://animal-db:5432/animal-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8081:8080"
    networks:
      - app-network

  specie-service:
    image: specie-service:0.0.1-SNAPSHOT
    build:
      context: ./specie-service
      dockerfile: dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://specie-db:5432/specie-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8082:8080"
    networks:
      - app-network
    depends_on:
      - animal-service
      - gateway-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-service:8080/api/animals"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  gateway-service:
    image: gateway-service:0.0.1-SNAPSHOT
    build:
      context: ./gateway-service
      dockerfile: dockerfile
    environment:
      - LABS_GATEWAY_HOST=gateway-service:8080
      - LABS_SPECIESERVICE_URL=http://specie-service:8080
      - LABS_ANIMALSERVICE_URL=http://animal-service:8080
    ports:
      - "8080:8080"
    networks:
      - app-network

  client-app:
    build:
      context: ./client-app
      dockerfile: dockerfile
    environment:
      - API_URL=http://gateway-service:8080/api
    ports:
      - "80:80"
    networks:
      - app-network

  specie-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=specie-database
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - specie-db-data:/var/lib/postgresql/data
    container_name: specie-db
    ports:
      - "5433:5432"
    networks:
      - app-network

  animal-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=animal-database
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - animal-db-data:/var/lib/postgresql/data
    container_name: animal-db
    ports:
      - "5434:5432"
    networks:
      - app-network

volumes:
  specie-db-data:
  animal-db-data:

networks:
  app-network:
    driver: bridge
