FROM eclipse-temurin:17.0.6_10-jre


ENV VERSION="0.0.1-SNAPSHOT"

ENV SERVER_PORT=8080


EXPOSE 8080

COPY target/specie-service-${VERSION}.jar /opt/specie-service/specie-service.jar
CMD ["java", "-jar", "/opt/specie-service/specie-service.jar"]
